site_name: Disability Science Theatre
repo_url: https://github.com/DisabilityScienceTheatre/resources
edit_uri: edit/main/docs/
site_url: https://DisabilityScienceTheatre.github.io/resources/
copyright: © DisabilityScienceTheatre 2022, All rights reserved
site_author: ntno

nav:
  - Home: 'index.md'
  - Before Your First Game: 'tools.md'
  - Classes:
      - Barbarian: 'classes/barbarian.md'
      - Fighter: 'classes/fighter.md'
      - Warlock: 'classes/warlock.md'
      - Paladin: 'classes/paladin.md'
      - Bard: 'classes/bard.md'
      - Monk: 'classes/monk.md'
      - Ranger: 'classes/ranger.md'
      - Rogue: 'classes/rogue.md'
      - Druid: 'classes/druid.md'
      - Cleric: 'classes/cleric.md'
      - Sorcerer: 'classes/sorcerer.md'
      - Wizard: 'classes/wizard.md'
      - Artificer: 'classes/artificer.md'
      - Bloodhunter: 'classes/bloodhunter.md'
  - Disability Specific Mechanics: 'disability-mechanics.md'
  - Extras: 
    - Actual Play Shows: 'shows.md'

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: "#"
  - attr_list

plugins:
  - search
  - git-revision-date

theme:
  name: material
  logo: assets/wheelchair-accessibility.png #Doug C. Hardester @r3volution11; accessibleicon.org

